<?php

abstract class TestCase extends Laravel\Lumen\Testing\TestCase
{
    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
